require "helper"

begin
  require "babosa"
rescue LoadError
  # Babosa is an optional development dependency; skip these tests without it.
end

if defined?(Babosa)
  # Uses the transliteration recipe documented in FriendlyId::Base and in the
  # initializer template generated by `rails generate friendly_id`, so that the
  # documented snippet cannot rot undetected.
  class Cyrillicist < ActiveRecord::Base
    self.table_name = "journalists"

    extend FriendlyId

    friendly_id :name, use: :slugged

    def normalize_friendly_id(text)
      text.to_slug.normalize! transliterate: [:russian, :latin]
    end
  end

  class BabosaTest < TestCaseClass
    include FriendlyId::Test

    test "should transliterate Russian Cyrillic to ASCII" do
      with_instance_of(Cyrillicist, name: "Крым") do |record|
        assert_equal "krym", record.slug
      end
    end

    test "should transliterate multi-word Cyrillic to ASCII" do
      with_instance_of(Cyrillicist, name: "Санкт-Петербург") do |record|
        assert_equal "sankt-peterburg", record.slug
      end
    end

    # Regression test: babosa ignores an option it does not recognise, so the
    # previously documented `:transliterations` left the text as it was.
    test "should not leave Cyrillic characters in the slug" do
      with_instance_of(Cyrillicist, name: "Москва") do |record|
        assert_equal "moskva", record.slug
        assert record.slug.ascii_only?, "expected an ASCII-only slug, got #{record.slug.inspect}"
      end
    end

    test "should fold accented Latin characters" do
      with_instance_of(Cyrillicist, name: "Café del Már") do |record|
        assert_equal "cafe-del-mar", record.slug
      end
    end

    test "should leave plain ASCII names alone" do
      with_instance_of(Cyrillicist, name: "Hello World") do |record|
        assert_equal "hello-world", record.slug
      end
    end

    # Only the named scripts are transliterated, so this recipe does not make
    # every slug ASCII. Pinned because the documentation says so.
    test "should leave scripts it was not asked to transliterate alone" do
      with_instance_of(Cyrillicist, name: "Αθήνα") do |record|
        assert_equal "αθήνα", record.slug
      end
    end
  end
end
