require "helper"

begin
  require "babosa"
rescue LoadError
  # Babosa is an optional development dependency; skip these tests without it.
end

if defined?(Babosa)
  # Uses the transliteration recipe documented in FriendlyId::Base and in the
  # initializer template generated by `rails generate friendly_id`. These tests
  # exist so that recipe cannot silently stop working when Babosa changes.
  class Cyrillicist < ActiveRecord::Base
    self.table_name = "journalists"

    extend FriendlyId
    friendly_id :name, use: :slugged

    def normalize_friendly_id(text)
      slug = text.to_slug
      slug.transliterate!(:russian, :latin)
      slug.to_ascii!
      slug.normalize!.to_s
    end
  end

  class BabosaTest < TestCaseClass
    include FriendlyId::Test

    test "should transliterate Russian Cyrillic to ASCII" do
      with_instance_of(Cyrillicist, name: "Крым") do |record|
        assert_equal "krym", record.slug
      end
    end

    test "should transliterate multi-word Cyrillic to ASCII" do
      with_instance_of(Cyrillicist, name: "Санкт-Петербург") do |record|
        assert_equal "sankt-peterburg", record.slug
      end
    end

    # Regression test: `normalize!` on its own preserves non-ASCII, so the
    # recipe needs `to_ascii!` to do what it claims.
    test "should not leave non-ASCII characters in the slug" do
      with_instance_of(Cyrillicist, name: "Москва") do |record|
        assert record.slug.ascii_only?, "expected an ASCII-only slug, got #{record.slug.inspect}"
      end
    end

    # Regression test: omitting :latin makes `to_ascii!` strip accented
    # characters rather than fold them, turning "Café" into "caf".
    test "should fold accented Latin characters rather than stripping them" do
      with_instance_of(Cyrillicist, name: "Café del Már") do |record|
        assert_equal "cafe-del-mar", record.slug
      end
    end

    test "should leave plain ASCII names alone" do
      with_instance_of(Cyrillicist, name: "Hello World") do |record|
        assert_equal "hello-world", record.slug
      end
    end
  end
end
