require "rom-sql"
require "friendly_id/core"
require "friendly_id/rom/configuration"
require "friendly_id/rom/relation"
require "friendly_id/rom/slug_scope"
require "friendly_id/rom/repo"

# FriendlyId's adapter for ROM, the persistence layer used by Hanami.
#
#     class Posts < Hanami::DB::Relation
#       schema :posts, infer: true
#       use :friendly_id, base: :title
#     end
#
#     class PostRepo < Hanami::DB::Repo
#       include FriendlyId::Rom::Repo
#
#       def find!(id) = posts.friendly.by_friendly_id(id).one!
#     end
#
#     repo.create_with_slug(title: "Hello World")  #=> #<Post slug="hello-world">
#
# Unlike the Active Record adapter, slugs are never generated by a callback,
# because ROM structs are immutable and have no lifecycle hooks. Ask for a slug
# and you get one; nothing happens implicitly on write.
#
# Note also that ROM has no equivalent of `to_param`. Pass the slug to your route
# helpers directly, e.g. `routes.path(:post, id: post.slug)`.
module FriendlyId
  module Rom
    # The value written to `friendly_id_slugs.scope` under the `:scoped` addon.
    #
    # Sorted so that the same record always serialises identically regardless of
    # the order the scope columns were declared in, matching
    # `Scoped#serialized_scope` on the Active Record side.
    def self.serialized_scope(config, values)
      config.scope_columns.sort.map { |column| "#{column}:#{values[column]}" }.join(",")
    end
  end
end

ROM.plugins do
  adapter(:sql) do
    register :friendly_id, FriendlyId::Rom::Relation, type: :relation
  end
end
